import type { Command, Option } from '@commander-js/extra-typings';

export interface OptionNode {
  long?: string;
  short?: string;
  description: string;
  takesValue: boolean;
  choices?: string[];
}

export interface CommandNode {
  name: string;
  aliases: string[];
  description: string;
  subcommands: CommandNode[];
  options: OptionNode[];
}

export function collectCommandTree(cmd: Command): CommandNode {
  const subcommands: CommandNode[] = [];
  for (const sub of cmd.commands) {
    const hidden = (sub as unknown as { _hidden?: boolean })._hidden;
    if (hidden) continue;
    subcommands.push(collectCommandTree(sub as Command));
  }

  const options: OptionNode[] = [];
  for (const opt of cmd.options as Option[]) {
    if (opt.hidden) continue;
    options.push({
      long: opt.long,
      short: opt.short,
      description: opt.description,
      takesValue: opt.required || opt.optional,
      choices: opt.argChoices,
    });
  }

  return {
    name: cmd.name(),
    aliases: cmd.aliases(),
    description: cmd.description(),
    subcommands,
    options,
  };
}

type FlatEntry = {
  path: string;
  subcommands: { name: string; description: string }[];
  options: OptionNode[];
};

function flattenTree(
  node: CommandNode,
  parentPath: string,
  globalOptions: OptionNode[],
): FlatEntry[] {
  const path = parentPath ? `${parentPath} ${node.name}` : node.name;
  const entries: FlatEntry[] = [];

  const subcommands: { name: string; description: string }[] = [];
  for (const sub of node.subcommands) {
    subcommands.push({ name: sub.name, description: sub.description });
    for (const alias of sub.aliases) {
      subcommands.push({ name: alias, description: sub.description });
    }
  }

  entries.push({ path, subcommands, options: [...node.options, ...globalOptions] });

  for (const sub of node.subcommands) {
    entries.push(...flattenTree(sub, path, globalOptions));
  }

  return entries;
}

function collectValueFlags(node: CommandNode): string[] {
  const flags = new Set<string>();
  function walk(n: CommandNode) {
    for (const opt of n.options) {
      if (opt.takesValue) {
        if (opt.long) flags.add(opt.long);
        if (opt.short) flags.add(opt.short);
      }
    }
    for (const sub of n.subcommands) walk(sub);
  }
  walk(node);
  return [...flags];
}

// --- Bash ---

export function generateBashCompletion(tree: CommandNode): string {
  const entries = flattenTree(tree, '', []);
  const lines: string[] = [];
  const name = tree.name;

  lines.push(`# bash completion for ${name}`);
  lines.push(`# Generated by: ${name} completion bash`);
  lines.push('');
  lines.push(`_${name}_completions() {`);
  lines.push('  local cur prev words cword');
  lines.push(
    '  if type _init_completion &>/dev/null; then _init_completion || return; else',
  );
  lines.push('    cur="${COMP_WORDS[COMP_CWORD]}"');
  lines.push('    prev="${COMP_WORDS[COMP_CWORD-1]}"');
  lines.push('    words=("${COMP_WORDS[@]}")');
  lines.push('    cword=$COMP_CWORD');
  lines.push('  fi');
  lines.push('');

  const valueFlags = collectValueFlags(tree);
  const valueFlagPattern = valueFlags.join('|');

  lines.push('  local cmd_path=""');
  lines.push('  local i=1');
  lines.push('  while [ $i -lt $cword ]; do');
  lines.push('    case "${words[$i]}" in');
  if (valueFlagPattern) {
    lines.push(`      ${valueFlagPattern}) i=$((i + 1)) ;;`);
  }
  lines.push('      -*) ;;');
  lines.push('      *) cmd_path="${cmd_path:+$cmd_path }${words[$i]}" ;;');
  lines.push('    esac');
  lines.push('    i=$((i + 1))');
  lines.push('  done');
  lines.push('');
  lines.push('  case "$cmd_path" in');

  for (const entry of entries) {
    const key =
      entry.path === tree.name ? '' : entry.path.replace(`${tree.name} `, '');
    const optFlags = entry.options
      .map((o) => o.long)
      .filter(Boolean)
      .join(' ');
    const subs = entry.subcommands.map((s) => s.name).join(' ');

    if (!optFlags && !subs) continue;

    lines.push(`    "${key}")`);
    if (optFlags) {
      lines.push('      if [[ "$cur" == -* ]]; then');
      lines.push(
        `        COMPREPLY=($(compgen -W "${optFlags}" -- "$cur")); return`,
      );
      lines.push('      fi');
    }
    if (subs) {
      lines.push(`      COMPREPLY=($(compgen -W "${subs}" -- "$cur"))`);
    }
    lines.push('      ;;');
  }

  lines.push('  esac');
  lines.push('}');
  lines.push('');
  lines.push(`complete -o default -F _${name}_completions ${name}`);

  return lines.join('\n');
}

// --- Zsh ---

function escapeZsh(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/:/g, '\\:');
}

export function generateZshCompletion(tree: CommandNode): string {
  const entries = flattenTree(tree, '', []);
  const lines: string[] = [];
  const name = tree.name;

  lines.push(`#compdef ${name}`);
  lines.push(`# zsh completion for ${name}`);
  lines.push(`# Generated by: ${name} completion zsh`);
  lines.push('');
  lines.push(`_${name}() {`);
  lines.push('  local cur prev cmd_path');
  lines.push('  cur="${words[$CURRENT]}"');
  lines.push('  prev="${words[$CURRENT-1]}"');
  lines.push('');

  const valueFlags = collectValueFlags(tree);
  const valueFlagPattern = valueFlags.join('|');

  lines.push('  cmd_path=""');
  lines.push('  for ((i=2; i < CURRENT; i++)); do');
  lines.push('    case "${words[$i]}" in');
  if (valueFlagPattern) {
    lines.push(`      ${valueFlagPattern}) ((i++)) ;;`);
  }
  lines.push('      -*) ;;');
  lines.push('      *) cmd_path="${cmd_path:+$cmd_path }${words[$i]}" ;;');
  lines.push('    esac');
  lines.push('  done');
  lines.push('');
  lines.push('  case "$cmd_path" in');

  for (const entry of entries) {
    const key =
      entry.path === tree.name ? '' : entry.path.replace(`${tree.name} `, '');
    const opts = entry.options.filter((o) => o.long);
    const hasSubs = entry.subcommands.length > 0;

    lines.push(`    "${key}")`);
    if (opts.length > 0) {
      lines.push('      if [[ "$cur" == -* ]]; then');
      const descs = opts
        .map((o) => `"${o.long}:${escapeZsh(o.description)}"`)
        .join(' ');
      lines.push(
        `        local -a opts=(${descs}); _describe 'option' opts; return`,
      );
      lines.push('      fi');
    }
    if (hasSubs) {
      const descs = entry.subcommands
        .map((s) => `"${s.name}:${escapeZsh(s.description)}"`)
        .join(' ');
      lines.push(`      local -a cmds=(${descs}); _describe 'command' cmds`);
    } else {
      lines.push('      _files');
    }
    lines.push('      ;;');
  }

  lines.push('  esac');
  lines.push('}');
  lines.push('');
  lines.push(`compdef _${name} ${name}`);

  return lines.join('\n');
}

// --- Fish ---

function escapeFish(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

export function generateFishCompletion(tree: CommandNode): string {
  const name = tree.name;
  const entries = flattenTree(tree, '', []);
  const lines: string[] = [];

  lines.push(`# fish completion for ${name}`);
  lines.push(`# Generated by: ${name} completion fish`);
  lines.push('');

  const rootEntry = entries[0];
  for (const sub of rootEntry.subcommands) {
    lines.push(
      `complete -c ${name} -n "__fish_use_subcommand" -a "${sub.name}" -d "${escapeFish(sub.description)}"`,
    );
  }

  for (const opt of tree.options) {
    if (opt.long) {
      const flag = opt.long.replace('--', '');
      let line = `complete -c ${name} -l "${flag}"`;
      if (opt.short) {
        line += ` -s "${opt.short.replace('-', '')}"`;
      }
      if (opt.takesValue) line += ' -r';
      if (opt.choices) line += ` -a "${opt.choices.join(' ')}"`;
      line += ` -d "${escapeFish(opt.description)}"`;
      lines.push(line);
    }
  }

  for (const entry of entries.slice(1)) {
    const parts = entry.path.split(' ').slice(1);
    const parentCmd = parts[parts.length - 1];
    const condition = `__fish_seen_subcommand_from ${parentCmd}`;

    for (const sub of entry.subcommands) {
      lines.push(
        `complete -c ${name} -n "${condition}" -a "${sub.name}" -d "${escapeFish(sub.description)}"`,
      );
    }

    for (const opt of entry.options) {
      if (opt.long) {
        const flag = opt.long.replace('--', '');
        let line = `complete -c ${name} -n "${condition}" -l "${flag}"`;
        if (opt.short) {
          line += ` -s "${opt.short.replace('-', '')}"`;
        }
        if (opt.takesValue) line += ' -r';
        if (opt.choices) line += ` -a "${opt.choices.join(' ')}"`;
        line += ` -d "${escapeFish(opt.description)}"`;
        lines.push(line);
      }
    }
  }

  return lines.join('\n');
}
